---
title: "Stranger Things Dialogue"
author: "Martijn van Bloois"
date: "2022-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
topic <- "Stranger-Things"
year <- 2022
week <- 42
yrwk <- glue::glue("{year}-{week}")
plots_dir <- paste0(year, "-", week)
fs::dir_create(here::here("plots", plots_dir))
png_file <- glue::glue("{yrwk}_{topic}.png")
pdf_file <- glue::glue("{yrwk}_{topic}.pdf")
```

```{r}
suppressMessages(library(tidyverse))
library(lubridate)
library(patchwork)
library(scales)
library(showtext)
library(prismatic)
``` 

```{r}
font_add_google(name = "Russo One", family = "russo")
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```


```{r}
tuesdata <- tidytuesdayR::tt_load(2022, week = 42)

episodes <- tuesdata$episodes
dialogues <- tuesdata$stranger_things_all_dialogue
rm(tuesdata)
```


```{r}
library(tidytext)
afinn <- get_sentiments("afinn")

orange <- "#f59705"
green <- "#075437"
background <- after_scale(clr_alpha(green, 0.2))

dialogues_cleaned <- dialogues %>% 
  filter(!is.na(dialogue)) %>% 
  unnest_tokens(word, dialogue) %>% 
  left_join(afinn) %>% 
  mutate(value = ifelse(is.na(value), 0 , value)) %>% 
  group_by(season, episode) %>% 
  mutate(sentiment = cumsum(value),
         season = glue::glue("S0{season}")) 

segments <- dialogues_cleaned %>% 
  group_by(season, episode) %>% 
  summarise(start_time = min(start_time),
            end_time = max(end_time),
            .groups = "drop")
```

```{r}
dialogues_cleaned %>% 
  ggplot(aes(x = start_time, y = sentiment, group = episode)) +
  geom_segment(data = segments,
               aes(x = start_time, xend = end_time, y = 0, yend = 0),
               size = 0.2,
               colour = green) +
  geom_line(colour = orange, size = .8) +
  scale_fill_gradient2(low = "red", mid = "white", high = "blue") +
  facet_grid(season ~ episode, scales = "free_x") +
  labs(x = NULL, y = NULL,
       title = "STRANGER THINGS",
       subtitle = "Cummulative sentiment in the dialogue over each episode",
       caption = "Source: 8flix.com prepared by Dan Fellowes & Jonathan Kitt") +
  theme_minimal() +
  theme(
    text = element_text(family = "russo",
                        colour = green),
    axis.text = element_text(colour = green),
    axis.text.x = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(size = 24,
                              hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    plot.background = element_rect(fill = background,
                                   colour = background),
    panel.grid = element_blank(),
    strip.text.y = element_text(hjust = 0.3),
    strip.text = element_text(colour = green)
  )


```


```{r}
ggsave(here::here("plots", yrwk, pdf_file),
      width = 8, height = 7, dpi = 300,
      device = cairo_pdf)

ggsave(here::here("plots", yrwk, png_file),
      width = 8, height = 7, dpi = 300, bg = "white",
      device = "png")
```


