---
title: "TidyTuesday 2022-24 -  by "
author: "Martijn van Bloois"
date: "`r Sys.Date()"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE,
                      dev = "cairo_pdf")
```

```{r this-week}
year <- lubridate::year(Sys.Date())
week <- lubridate::week(Sys.Date())
plots_dir <- paste0("plots/", year, "-", week)
fs::dir_create(plots_dir)
png_file <- "2022-25_Juneteenth.png"
pdf_file <- "2022-25_Juneteenth.pdf"
```


```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(janitor)
library(scales)
library(ggtext)
library(patchwork)
library(showtext)
font_add_google(name = "IBM Plex Sans", family = "ibm-plex-sans")
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```

```{r data-load}
tuesdata <- tidytuesdayR::tt_load(year, week = week)

firsts <- tuesdata$firsts

# blackpast <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/blackpast.csv')
# census <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/census.csv')
# slave_routes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/slave_routes.csv')
# african_names <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/african_names.csv')

```

```{r data-prep}
firsts %>%
  count(category)

firsts_tbl <- firsts %>%
  filter(year > 1799) %>% 
  filter(year < 1900) %>% 
  mutate(person = str_replace_all(person, "\\[[0-9]+\\]", ""),
         person = str_replace_all(person, "\\[Note [0-9]+\\]", ""),
         person = str_remove(person, " \\(See also"),
         person = str_remove(person, ", renamed Lincoln University.+$"),
         person = str_remove(person, ", who was educated at the University.+$"),
         person = str_remove(person, ", based in Philadelphia.+$"),
         person = str_remove(person, " founded in Philadelphia.+$"),
         person = str_remove(person, ", Belgium.+$"),
         person = str_remove(person, ", The Laughing.+$"),
         person = str_remove(person, ", hired by.+$"),
         person = str_remove(person, " His opponent contested.+$"),
         person = str_remove(person, ", then living.+$"),
         person = str_remove(person, "; Xenia.+$"),
         person = str_remove(person, "founded in New York City by "),
         person = str_replace_all(person, " \\(.+\\)", ""),
         person = str_remove(person, "\\.$"),
         accomplishment = str_remove(accomplishment, "First African-American"),
         accomplishment = str_remove(accomplishment, "^First "),
         accomplishment = str_remove(accomplishment, "African-American "),
         accomplishment = str_replace(accomplishment, "woman", "female")
         ) %>% 
  group_by(year) %>% 
  sample_n(1)
```

```{r plotting}
black <- 		"#000000"
brown <-  	"#654321"
tan 	<-  	"#d2b48c"
gold 	<- 	"#ffd700"
pink 	<-  	"#ffc0cb"
crimson <-  	"#dc143c"
green <- 	 	"#00aa00"
blue 	<-  	"#4682b4"

fill_cols <- c(
  "Religion" = crimson,
  "Education & Science" = brown,
  "Law" = blue,
  "Military" = green,
  "Politics" = black,
  "Social & Jobs" = pink,
  "Sports" = gold,
  "Arts & Entertainment" = tan
)

subtitle <- "FIRST AFRICAN-AMERICAN ..."
title <-
  "African-American accomplishments in the nineteenth century"
caption <- "Source: adapted from Wikipedia"

plt_1 <-
  firsts_tbl %>%
  ggplot() +
  geom_hline(aes(yintercept = 0), linetype = 2) +
  geom_label(
    aes(
      x = year,
      y = 0,
      label = year,
      fill = category
    ),
    color = "white",
    label.r = unit(0.5, "lines"),
  ) +
  scale_fill_manual(values = fill_cols) +
  geom_text(aes(x = year, y = .5, label = person),
            hjust = "left",
            size = 4) +
  geom_text(aes(x = year, y = -.5, label = accomplishment),
            hjust = "right",
            size = 4) +
  scale_x_reverse() +
  scale_y_continuous(limits = c(-5, 5)) +
  labs(
    title = title,
    subtitle = subtitle,
    caption = caption,
    x = NULL,
    y = NULL
  ) +
  coord_flip() +
  theme_minimal() +
  theme(
    text = element_text(family = "ibm-plex-sans"),
    plot.title = element_text(
      family = "ibm-plex-sans",
      size = 20,
      hjust = 0.5
    ),
    plot.subtitle = element_text(
      family = "ibm-plex-sans",
      face = "bold",
      size = 28,
      hjust = 0.5
    ),
    axis.text = element_blank(),
    axis.line = element_blank(),
    panel.grid = element_blank(),
    plot.background = element_rect(fill = "#ede5dc"),
    legend.position = "bottom"
  )
```

```{r full-panel, fig.width = 12, fig.height = 20}
plt_1 + plot_layout(ncol = 1)

ggsave(here::here(plots_dir, pdf_file),
      width = 12, height = 20, dpi = 300,
      device = cairo_pdf)

ggsave(here::here(plots_dir, png_file),
      width = 12, height = 20, dpi = 300,
      device = "png")
```

***

```{r session-info}
sessionInfo()
```