---
title: "Bigfoot"
author: "Martijn van Bloois"
date: "2022-09-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
topic <- "Bigfoot"
year <- 2022
week <- 37
yrwk <- glue::glue("{year}-{week}")
plots_dir <- paste0(year, "-", week)
fs::dir_create(here::here("plots", plots_dir))
png_file <- glue::glue("{yrwk}_{topic}.png")
pdf_file <- glue::glue("{yrwk}_{topic}.pdf")
```

```{r}
suppressMessages(library(tidyverse))
library(lubridate)
library(patchwork)
library(scales)
library(showtext)
``` 

```{r}
font_add_google(name = "Dancing Script", family = "title-font")
font_add_google(name = "Cabin", family = "main-font")
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
```

```{r}
# colours
c_text <- "#ededed"
c_background <- "#36454f"
```


```{r}
theme_set(theme_minimal())

theme_update(
    text = element_text(family = "main-font",
                        colour = c_text),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    axis.text.x = element_text(face = "bold",
                               colour = c_text,
                               size = 14),
    axis.text.y = element_text(face = "bold",
                               colour = c_text,
                               size = 14,
                               vjust = -0.1),
    plot.background = element_rect(fill = c_background,
                                   colour = NA),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    plot.title.position = "plot"
)
```


```{r}
bigfoot <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-13/bigfoot.csv')
```


```{r}
states <- map_data("state", col = "grey40")
```

``` {r}
plt_map <- bigfoot %>% 
  filter(year(date) >= 1950) %>% 
  filter(longitude > -130) %>% 
  ggplot(aes(x = longitude, y = latitude)) +
  geom_polygon(data = states,
               aes(x = long, y = lat, group = group),
               fill = c_background, colour = "grey50") +
  geom_point(colour = "#40FF00", size = 1, alpha = .2) +
  labs(x = NULL, y = NULL) +
  theme_void()+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        plot.background = element_rect(fill = c_background, colour = c_background))+
  coord_map("albers",  lat0 = 45.5, lat1 = 29.5)
``` 

``` {r}

c_seasons <- c("FALL" = "#804000", "SPRING" = "#40C000", "WINTER" = "#40C0FF", "SUMMER" = "#FFC000")

plt_season <- bigfoot %>% 
  filter(year(date) >= 1950) %>% 
  filter(season != "Unknown") %>% 
  mutate(season = str_to_upper(season),
         season = factor(season,
                         levels = c("SPRING", "SUMMER", "FALL", "WINTER"))
         ) %>% 
  group_by(season) %>% 
  summarise(n = n()) %>% 
  ggplot(aes(x = season, y = n, fill = season)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c_seasons) +
  labs(x = NULL, y = NULL) 

plt_time <- bigfoot %>% 
  group_by(year = year(date)) %>% 
  summarise(n = n()) %>% 
  filter(year >= 1950) %>% 
  ggplot(aes(x = year, y = n)) +
  geom_col(fill =  "#40FF00", show.legend = FALSE) +
  labs(x = NULL, y = NULL) 
```

```{r}
plt_time / (plt_season +  plt_map) +
  plot_annotation(
    title = "BIGFOOT SIGHTINGS",
    subtitle = str_wrap("Bigfoot sightings peaked in 2004. Washington State has the most sightings since 1950, followed by Ohio,
    Florida and California. Summer is the best time for a sighting.", width = 90),
    caption = "Source: Bigfoot Field Research Organisation",
    theme = theme(plot.title = element_text(size = 36, face = "bold"),
                  plot.subtitle = element_text(size = 18),
                  plot.caption = element_text(size = 12))
  )

ggsave(here::here("plots", yrwk, pdf_file),
      width = 12, height = 8, dpi = 300,
      device = cairo_pdf)

ggsave(here::here("plots", yrwk, png_file),
      width = 12, height = 8, dpi = 300,
      device = "png")
```


